<?php
return [
    'biotime' => [
        'api_token' => 'd7fd11e694764fb29af32c3a4032dcfb',
        'transactions_url' => 'http://65.108.192.26:8204/api_gettransctions',
        // production
        'start_time' => date('Y-m-d H:i:s', strtotime('-5 minutes')),
        'end_time' => date('Y-m-d H:i:s'),
        // testing
        // 'start_time' => '2026-01-27 00:00:00',
        // 'end_time' => '2026-01-27 23:59:59',
    ],
    'bitrix' => [
        'user_map' => [
            5 => 59,    // Islam Shokuev
            8 => 25,    // Stanislav Maltsev
            15 => 9,    // Zaira Nasirtinova
            16 => 38,   // Vladislav Tikolaz
            20 => 35,   // Natalia Magomedova
            30 => 13,   // Siyovush Mirzoev
            32 => 18,   // Ayya Prokopyeva
            46 => 57,   // Bulat Akhmedov
            53 => 24,   // Diana Goginava
            72 => 20,   // Rezuan Shokuev
            199 => 12,  // Julia Kravchenko
            377 => 48,  // Elena Soina
            383 => 57,  // Bulat Akhmedov
            402 => 82,  // Numan Ahamed
            405 => 36,  // Karl Lontoc
            410 => 75,  // Fatimat Batyrova
            416 => 61,  // Irina Lobanova
            422 => 49,  // Navneet Kaur
            424 => 50,  // Aelita Akhmedova
            426 => 30,  // Cindy Nacario

            1 => 0,     // Gayeyelman
            2 => 0,     // Salamabou Ajram
            3 => 0,     // Jameshbouss
            13 => 0,    // Mohammad Fahad
            14 => 0,    // Megna Pankaj
            18 => 0,    // Asiyat Bberbekova
            25 => 0,    // Abdur Rahim
            26 => 0,    // Abidullah Subhan
            29 => 0,    // Daphne Verghese
            35 => 0,    // Pavel Piantcev
            36 => 0,    // Liudmyla Nykolaichuk
            38 => 0,    // Evgeniia Odintsova
            39 => 0,    // Alena Kazeka
            40 => 0,    // Anastasia Skulanova
            43 => 0,    // Emil Gabibov
            45 => 0,    // Ziyarzayev
            47 => 0,    // Mariadeleon
            54 => 0,    // Philipp Morgunov
            56 => 0,    // Kalima Iskanova
            57 => 0,    // Mohammad Alshibi
            62 => 0,    // Artem Obukhov
            63 => 0,    // Magomed Musaev
            64 => 0,    // Mohamad Takriti
            66 => 0,    // Kristina Boeva
            68 => 0,    // Dmitrii Shishov
            69 => 0,    // Roman Skvortsov
            71 => 0,    // Mariia Khmyz
            76 => 0,    // Pavel Dragovalovskii
            79 => 0,    // Farah Warda
            81 => 0,    // Guzel Musabirova
            83 => 0,    // Timur Chimaev
            84 => 0,    // Marina Dolgova
            85 => 0,    // Jana Kali
            87 => 0,    // Magomed Mamaev
            88 => 0,    // Aslan Safarov
            90 => 0,    // Sevilya Velieva
            92 => 0,    // Dafne Cavalieri
            106 => 0,   // Ahmed Riad Bukkerou
            107 => 0,   // Victoria Banar
            111 => 0,   // Christopher Bayuda
            119 => 0,   // Alexey Chernikov
            127 => 0,   // Oleg Mudrak
            132 => 0,   // Nika Bilikhodze
            136 => 0,   // David Ijod
            141 => 0,   // Mohamed Wais
            144 => 0,   // Alina Volcharenko
            146 => 0,   // Svitlana Svitlichnaya
            157 => 0,   // Oleg Andronyuk
            159 => 0,   // Daria Lukianova
            172 => 0,   // Abdul Manaf Alathurayil Kunhimon Aboobacker
            173 => 0,   // Mohammed Fawas Maram Parambil
            175 => 0,   // Violetta Dokshukina
            187 => 0,   // Irina Lungu
            190 => 0,   // Shamkyz Dinaeva
            191 => 0,   // Mhonabel De Leon
            193 => 0,   // Mehri Sadikova
            196 => 0,   // Amina Elsaid
            198 => 0,   // Marina Dolgova
            201 => 0,   // Zhanara Kali
            204 => 0,   // Sanjay Sachdeva
            205 => 0,   // Daniel Burkin
            206 => 0,   // Rahmathulla Khan
            208 => 0,   // Aswathi Avayil
            222 => 0,   // Sameh Maher
            223 => 0,   // Anarakul Mambetova
            227 => 0,   // Alikhan Bitokov
            236 => 0,   // Murad Ramazanov
            244 => 0,   // Muhammad Bilal Raja
            246 => 0,   // Maria Salloum
            247 => 0,   // Muhammad Alsarah
            248 => 0,   // Mukhammad Jon Olimov
            249 => 0,   // Baraa Fouzi Salem
            259 => 0,   // Abdelhady Khodir
            260 => 0,   // Beshier Elawella
            261 => 0,   // Ainurbek Bauova
            262 => 0,   // Arsalan Jani
            263 => 0,   // Usman Bin Aamir
            264 => 0,   // Gayda Magomedova
            265 => 0,   // Surendra Singh
            266 => 0,   // Ubeida Al Haj
            267 => 0,   // Ibrakhim Ilyassov
            268 => 0,   // Valerii Khachatrian
            269 => 0,   // Yulia Burdiak
            270 => 0,   // Tina Al Muhtashem
            271 => 0,   // Mayya Atayeva
            272 => 0,   // Ahmad Alqudsi
            273 => 0,   // Ibrahim Rajab
            274 => 0,   // Adil Amanzholov
            275 => 0,   // Rafiulah Khan
            276 => 0,   // Bhawishay Balani
            277 => 0,   // Habibah Assabelnaby
            278 => 0,   // Michel Saab
            281 => 0,   // Imran Memon
            286 => 0,   // Sajjad Memon
            288 => 0,   // Aleksei Bobko
            301 => 0,   // Denis Kazaryan
            305 => 0,   // Tatyana Lupatnikova
            307 => 0,   // Pedram Gholami
            325 => 0,   // Safwan Zaheer
            326 => 0,   // Hasan Malakha
            327 => 0,   // Simple Adatiya
            328 => 0,   // Khurram Riaz
            329 => 0,   // Dinoza Rakhimova
            330 => 0,   // Waqas Asghar
            331 => 0,   // Qasim Zainli
            332 => 0,   // Muhammad Abdullah
            333 => 0,   // Leena Vatnani
            335 => 0,   // Imane Elfadil
            336 => 0,   // Abu Sufyan
            341 => 0,   // Chaminda Liyana Ralalage
            342 => 0,   // Moath Shita
            350 => 0,   // Olga Kim
            353 => 0,   // Belshri Brahma
            357 => 0,   // Vasiliy Tovarnytskyy
            366 => 0,   // Rza Hajiyev
            372 => 0,   // Obiefuna Isaiah
            375 => 0,   // Salam Qasem
            384 => 0,   // Sunny Gambhir
            406 => 0,   // Jeffrey Garcia
            415 => 0,   // Ksenia Zhikhareva
            417 => 0,   // Priyanka Singh
            423 => 0,   // Rehmat Ullah
            427 => 0,   // Anton Kurokhtin
            77777 => 0, // Test
        ],
        'biotime_transactions_entity_type_id' => 1060,
    ],
    'timezone' => 'Asia/Dubai',
    'log_timezone' => 'Asia/Kolkata',
];
